FROM quay.io/lrossett/rpmbuild-base-toolbox:f41

USER root

RUN dnf install -y \
python3 \
python3-devel \
python3-pip \
python3-rpm \
python3-rpm-generators \
python3-rpm-macros \
python3-rpmautospec \
python3-rpmconf \
python3-rpmconf-doc \
python3-rpmdeplint

USER 1001
