FROM localhost/base-box:latest

RUN dnf config-manager -y --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo

RUN dnf install -y \
wget \
skopeo \
python3 python3-pip python3-devel virtualenv \
ansible terraform

RUN pip3 install molecule
