FROM quay.io/fedora/fedora:39

ARG KAS_URL=https://github.com/siemens/kas/archive/refs/heads/master.zip

RUN dnf install -y \
tar \
vim \
gawk \
wget \
git \
diffstat \
unzip \
texinfo \
gcc \
chrpath \
socat \
cpio \
python3 \
python3-pip \
python3-pexpect \
xz-libs \
net-tools \
python3-GitPython \
python3-jinja2 \
mesa-libGL \
sdl12-compat-devel \
python3-subunit \
zstd \
lz4 \
lz4-libs \
file \
libacl-devel \
glibc-langpack-en \
which \
g++ \
patch \
hostname \
rpcgen \
bzip2 \
perl-Thread-Queue \
perl-File-Compare \
perl-FindBin \
perl-open.noarch

RUN pip3 install ${KAS_URL}
