#!/usr/bin/env bash

printe() {
  local emsg="${1}"
  local ecode="${2}"

  echo "[ERR] ${emsg}" 1>&2

  if [ ! -z "${ecode}" ]; then
    exit ${ecode}
  fi
}

cmd_build() {
  local images_dir="${1}"
  local img_name="${2}"

  if [ -z "${img_name}" ]; then
    printe "Cannot build image without a name." 1
  fi

  local img_dir="${images_dir}/${img_name}"

  if [ ! -d ${img_dir} ]; then
    printe "Directory not found: ${img_dir}" 1
  fi

  echo "[INFO} Building: ${img_dir}"

  podman build -t localhost/${img_name}:latest -f ${img_dir}/Containerfile
}

if [ -z "${TB_MGR_IMAGES_DIR}" ]; then
  printe '"TB_MGR_IMAGES_DIR" environment variable not defined.' 1
fi

cmd_build "${TB_MGR_IMAGES_DIR}" "${1}" 
